### PR TITLE
PKG: Fix potential security vulnerabilities in dependencies

### PR DESCRIPTION
**Pull request by hoechenberger**
- Update `react-dom` and `bootstrap`
- [x] I have updated `CHANGES.md`

### CODE REVIEW

**Comment by ArndalAndersen** [comment]
Unfortunately, the updates mess with the styling of especially the frontend build. I don't have a fix just yet.

**Comment by hoechenberger** [comment]
Argh I suspected it!! Damn :(

**Comment by hoechenberger** [comment]
I can try to make a new PR for the `bootstrap` and another for the `react-dom` update, so we could test their effects separately...

**Comment by hoechenberger** [comment]
Btw, how did you test this? I usually delete my entire `node_modules` directory and run `npm install` to re-create it freshly...

**Comment by ArndalAndersen** [comment]
I pulled this `security` branch, rebased it on the current master and ran `npm install`. I made it so far as to fix the frontend in its development version, but could not get the build version to look nice. I don't think I can fix it.

**Pull request closed without merging**
